### ISSUE TITLE
Remove Blender objects belonging to removed MBDyn nodes

### ISSUE THREAD

**Issue by zanoni-mbdyn** [zanoni-mbdyn/blendyn#9] opened 2017-03-16 13:26 UTC
From a [this issue](https://github.com/zanoni-mbdyn/blendyn/pull/7), now closed: 

Check, when re-loading the .log file, if a node or an element associated to some Blender object present in the scene has been removed from the MBDyn input file, and remove both the reference to the entity in the bpy.context.scene.mbdyn.{nodes,elems} dictionaries and the corresponding Blender object in the scene.

> [...] it is probably better to tackle it when the user loads the .log file after having done so already. Off the top of my head, we could flag all the nodes/elements as "not imported" before re-reading the .log file (there is an is_imported Bool Property in the MBDynNodesDictionary and MBDynElemsDictionary collection properties), flag them as "imported" as we find them in the .log file, and then check which one are left as "not imported" at the end of the process, and get rid of them.

**Comment by janga1997** [comment] 2017-03-16 15:34
@zanoni-mbdyn One thing I am not sure about this issue, and blendyn in general, is how are nodes are added to `context.scene.mbdyn.nodes` ?
In `set_motion_paths_mov()` and `set_motion_paths_netcdf()` in `baselib.py`, I see 
```
    scene = context.scene
    mbs = scene.mbdyn
    nd = mbs.nodes
```
And then I see
```
    anim_nodes = list()
    for node in nd:
        if node.blender_object != 'none':
            anim_nodes.append(node.name)
```

Without ever something being assigned to `nodes`.?
What is happening here?

**Comment by louisgag** [comment] 2017-03-17 06:25
As for removing the Blender object, are we sure we want to do that? Perhaps a confirmation dialog would be adequate as I can see potentially unwanted consequences of removing a Blender object that a user might not necessarily want to delete... Perhaps a simpler solution than the dialog box would be to hide the object?

**Comment by janga1997** [comment] 2017-03-17 07:06
But if the user specifically took the pain to remove specific nodes from the mbd file, shouldn't we register those changes?

**Comment by louisgag** [comment] 2017-03-17 08:07
Yes, I think it is a great idea to resister the changes, but think of this example, maybe extreme but still to consider:
- I have a car model with 4 tires, modeled in MBDyn
- I want to test the response without the tires, or even worst, I mistakenly load another car model without the tires
- That was my only Blender file and now I lost my Blender object for the tires and I might have spent a few hours making those tires good looking..
Regards,

**Comment by janga1997** [comment] 2017-03-17 08:20
Well, then your suggestion of hiding the objects would be good enough i assume?

**Comment by janga1997** [comment] 2017-03-17 08:23
Wait , but hiding the objects doesn't really remove them from the scene, and they can still interfare with the motion of the rest of the objects, right?

**Comment by louisgag** [comment] 2017-03-17 08:23
Most likely, yes :) 
@zanoni-mbdyn any comments/preferences ?

**Comment by louisgag** [comment] 2017-03-17 08:23
what do you mean by "interfere"?

**Comment by janga1997** [comment] 2017-03-17 08:26
I am not completely sure about how blender works, but i assume objects "collide" with each other?

**Comment by louisgag** [comment] 2017-03-17 08:26
No, that shouldn't be an issue, objects (and frames) do not interact together (at least as long as you stay away from the game or physics engine)

**Comment by zanoni-mbdyn** [comment] 2017-03-17 09:34
Hiding them could be a good choice, I guess... But it is better to do so only if the user has given his consent. The dialog box warning the user that a number of nodes/elements have been removed from the model is a good idea. 

The user might be presented with the list of the nodes that are not found anymore, and asked if he wants to remove the related Blender objects or not.

**Comment by louisgag** [comment] 2017-03-17 09:50
Yes, the 
> list of nodes

idea seem to me the best solution.

**Comment by louisgag** [comment] 2017-03-21 10:00
In the current version of the addon I am no longer able to change result file.
Upon clicking "Select results file" on a Blender file which has already loaded a previous results file, I systematically get this, even when reselecting the same results file:


```
Error, region type 5 missing in - name:"File", id:5
Error, region type 6 missing in - name:"File", id:5
Traceback (most recent call last):
  File "/home/louis/.config/blender/2.69/scripts/addons/blendyn-master/base.py", line 539, in execute
    remove_oldframes(context)
  File "/home/louis/.config/blender/2.69/scripts/addons/blendyn-master/baselib.py", line 283, in remove_oldframes
    obj_list = [bpy.data.objects[var] for var in obj_names]
  File "/home/louis/.config/blender/2.69/scripts/addons/blendyn-master/baselib.py", line 283, in <listcomp>
    obj_list = [bpy.data.objects[var] for var in obj_names]
KeyError: 'bpy_prop_collection[key]: key "none" not found'

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by janga1997** [comment] 2017-03-21 10:16
@louisgag You mean **only the changes** in #7 ?
Can you trace your steps for me?
The error seems to be that the nodes currently in the scene do not have a corresponding object. I can't see how that could happen.

**Comment by janga1997** [comment] 2017-03-21 10:20
@louisgag I got your error now.
I made the assumption that when a user selects a results file for the first time, he would definitely add objects to the scene and animate , before selecting a new results file.
You seem to have selected a new results without doing anything else, so there are no objects to clear data from. That's why it shows up an error of `none` because no Blender objects exist yet.

I will fix that in this PR.

Nice find!

**Comment by louisgag** [comment] 2017-03-21 10:34
@janga1997 
Ok thanks, and I'll try it using totally clean files because I've been using an old file relinked to MBDyn nodes after having done "CLEAR MBDYN DATA"...

**Comment by janga1997** [comment] 2017-03-21 10:37
@louisgag 
I just purged `obj_names` of any `"none"` strings before going any further.

**Comment by louisgag** [comment] 2017-03-21 14:50
@janga1997 
I've tried with a clean file, and it does the same. I can confirm that, as you pointed out, the issue is only present when some nodes have not been assigned to objects. Perhaps your pull request already addresses that..

**Comment by janga1997** [comment] 2017-03-21 14:53
@louisgag I added a [commit](https://github.com/zanoni-mbdyn/blendyn/pull/10/commits/484fe9e60c3c726351c377a29c03367c82331a6e) to the PR of this issue. That solves the error.

**Comment by zanoni-mbdyn** [comment] 2017-03-21 17:26
@janga1997  Have you tested it? Unfortunately I have no time right now to test this myself...

**Comment by janga1997** [comment] 2017-03-21 17:43
@zanoni-mbdyn I have tested it. And it works. Could you reply to a query on the PR itself?

**Closed as completed** 2017-03-27 12:41 UTC
