### ISSUE TITLE
 visualization offset error for both body and joint

### ISSUE THREAD

**Issue by kuwt** [zanoni-mbdyn/blendyn#54] opened 2023-08-03 22:34 UTC
I downloaded the zip and I used blender 2.80. And I followed the pendulum tutorial second case(https://www.mbdyn.org/userfiles/documents/tutorials.pdf) so here is my mbd file. From the case, the body should be at the same position as the node while the joint should be at the origin. But in my blendyn, I have the joint at the node while the body somewhere below the node.    
 
```
begin: data;
    problem: initial value; # the default
end: data;

begin: initial value;
    initial time: 0.;
    final time: 1.;
    time step: 1.e-3;
    max iterations: 10;
    tolerance: 1.e-6;
end: initial value;

begin: control data;
    structural nodes:
        +1 # node in the constraint
    ;
    rigid bodies:
        +1 # node in the constraint
    ;
    joints:
        +1 # node in the constraint: revolute
    ;
    gravity;
end: control data;

set: integer Pendulum = 1;
set: integer Mass = 2;
set: real M = 1.;
set: real L = .5;
set: real Omega0 = .2;

reference: Pendulum,
    reference, global, null,
    reference, global, eye,
    reference, global, null,
    reference, global, 0., Omega0, 0.;
reference: Mass,
    reference, Pendulum, 0., 0., -L,
    reference, Pendulum, eye,
    reference, Pendulum, null,
    reference, Pendulum, null;

begin: nodes;
    structural: 2000+Mass, dynamic,
        reference, Mass, null,
        reference, Mass, eye,
        reference, Mass, null,
        reference, Mass, null;
    # no dynamic dofs (it will be fully grounded)
end: nodes;

begin: elements;
    body: 2000+Mass, 2000+Mass,
        M,
        reference, Mass, null,
        null; 
        /* The problem is non-singular
        * because of the constraint */
    joint: 2000+Mass, revolute pin,
        2000+Mass,
        reference, Pendulum, null,
        hinge, reference, Pendulum,
        1, 1.,0.,0., 3, 0.,1.,0.,
        reference, Pendulum, null,
        hinge, reference, Pendulum,
        1, 1.,0.,0., 3, 0.,1.,0.;

    gravity: 0., 0., -1., const, 9.81;
end: elements;

```

![image](https://github.com/zanoni-mbdyn/blendyn/assets/20258451/1ca6f63f-037b-4ded-92f7-c68db825ef5c)

**Comment by zanoni-mbdyn** [comment] 2023-08-22 18:50
Hello @kuwt, can you please try with a more recent version of Blender? I have no issues with the lastest available in my distro, which is the 3.6.0.

Thanks!

![image](https://github.com/zanoni-mbdyn/blendyn/assets/7814088/0dfc50d3-efaf-4b8c-86ca-93f361237fe6)

**Comment by kuwt** [comment] 2023-08-23 12:02
I have to find some time to try that again. Thank you for the advice.

**Comment by zanoni-mbdyn** [comment] 2023-11-15 15:42
Closing (can't reproduce).

**Closed as not planned by zanoni-mbdyn** 2023-11-15 15:42 UTC
