### ISSUE TITLE
blendyn-master not working & blendyn-bugfix error uploading input file

### ISSUE THREAD

**Issue by lidiaperezt** [zanoni-mbdyn/blendyn#53] opened 2023-03-27 14:13 UTC
I am running Blender 3.4 on Windows 10, and I am having some trouble with Blendyn.
 
1. I tried installing the branch blendyn-master branch. However, it doesn't allow me to enable this add-on. I was wondering why.
2. Instead, I installed the blendyn-bugfix branch and I installed dependencies on netcdf4. However, when I import the input file the error in the next photo arises. Apparently it goes away when I click on the "load .log file" button (is it normal?). 

![error](https://user-images.githubusercontent.com/129078799/227964214-9fdf6538-1ef1-4289-b039-29adeb6457fd.png)

Then, when I animate the node, everything appears to work but actually no animation is created (meaning in the timeline my animation is a point, so the node doesn't follow the motion it is supposed to follow). I also run the mbdyn file with Matlab and plotted the motion to check the .nc file is in order and I think it is, since I get good motion plots in Matlab. Therefore, I was wondering if maybe I am doing something wrong? 

I upload also my input file in case it is needed. 
[rigidbody.txt](https://github.com/zanoni-mbdyn/blendyn/files/11079554/rigidbody.txt)

Thank you in advance,
Lidia

**Comment by zanoni-mbdyn** [comment] 2023-06-10 14:25
Thank you for posting this issue, and excuse me for not having noticed it before! My Github notification went in the spam folder of my email for some reason.

Do you still have the problem? For the moment, I cannot reproduce it.

**Comment by zanoni-mbdyn** [comment] 2023-06-15 14:56
The problem is, however, that you don't have the `netCDF` Python module installed and working properly. 
[Here](https://github.com/zanoni-mbdyn/blendyn/wiki/Installing-Blendyn#optional-packages) you can find the instructions to install them. If you did follow what is written here and still experience problems, I'm afraid the problem might be in your Python installation.

**Comment by zanoni-mbdyn** [comment] 2023-08-22 18:47
Closing the issue.

**Closed as completed by zanoni-mbdyn** 2023-08-22 18:47 UTC
