### ISSUE TITLE
Blender 2.82 - Different UI

### ISSUE THREAD

**Issue by mr-intj-22** [zanoni-mbdyn/blendyn#41] opened 2020-03-15 20:17 UTC
the tutorial shows UI of Blender that is different than the UI of the newest version "2.82".
of course I installed the Blendyn addone and it is there but couldn't access the Blendyn features from the toolbar since it does not show up (which is already mentioned in the main page).

Usually it should show up in the animation toolbar, right? Even clicking 'N' doesn't bring it up!

here are screenshots to understand more what is going on.

The blendyn addone installed
![the blendyn addone installed](https://user-images.githubusercontent.com/27434236/76709729-64ae6380-6701-11ea-8b78-3662a67197f4.png)

The blendyn "features" show up but No 'Load Results'
![the blendy feature show up but No 'Load Results'](https://user-images.githubusercontent.com/27434236/76709732-6b3cdb00-6701-11ea-9674-654582e5c04b.png)

When 'N' is pressed
![When 'N' is pressed](https://user-images.githubusercontent.com/27434236/76709821-19e11b80-6702-11ea-8e0b-6212a25457f0.png)

What could be wrong? did I mess up the installation?

In the meantime, I will try to install Blender v2.7* from source and use the older version, but it should be a temporary solution.

**Comment by louisgag** [comment] 2020-03-16 10:56
Hi,
At first glance it seems your installation is fine.
In the last screenshot you should have something like this:
![Screenshot from 2020-03-16 11-51-33](https://user-images.githubusercontent.com/12291709/76749547-f0b1a100-677c-11ea-954a-dd5a84dd84ee.png)
Are you sure everything remained the same (the plugin loaded for example) between scrfeenshots 1&2 and screenshot 3?
In that case, maybe a terminal output would help (ie: load blender from terminal and paste the output here).

**Comment by zanoni-mbdyn** [comment] 2020-03-16 16:11
@mr-intj-22 which branch did you download? Can you try do download the code of the `devel` branch, if you have not done so?

Also, to help us understand what it is happening, can you please open Blender from the command line and report what is the output there, at startup and when you deactivate/activate Blendyn?

Cheers,
Andrea

**Comment by mr-intj-22** [comment] 2020-03-16 20:19
@zanoni-mbdyn I downloader from the Master branch. I did as you asked and the terminal is showing three libraries that couldn't find (netCDF4, Pygal, Psutil).
the interesting part is that, all python versions have 2.7, 3.6 and 3.7 (annoying!).

![Screenshot from 2020-03-16 18-18-13](https://user-images.githubusercontent.com/27434236/76795705-2cbf2300-67ca-11ea-8e98-c3d8813e50a0.png)

I have managed to get rid of those errors but got new ones instead (Yikes)
even devel branch didn't work!

![Screenshot from 2020-03-16 21-14-22](https://user-images.githubusercontent.com/27434236/76796172-2bdac100-67cb-11ea-90a0-d87f69897d6b.png)

FYI, I settled on Python 3.7 lastly, Blendyn downloaded from 'devel' branch and Blender v2.83.

Still can't see 'load results'.

### Update
Blendy appeared on the side menu, clicking on it throws an error (more Yikes!)

![Screenshot from 2020-03-16 21-18-35](https://user-images.githubusercontent.com/27434236/76796555-026e6500-67cc-11ea-9de6-e1669c2df984.png)

Blender Crash Log:
[blender.crash.txt](https://github.com/zanoni-mbdyn/blendyn/files/4340216/blender.crash.txt)

I hope I gave you enough input to sort the problem out!

**Comment by zanoni-mbdyn** [comment] 2020-03-16 22:04
Which distro are you on? It seems that you are installing Blender using the binary packages: this is not recommmended, as the packages contain a bundled version of Python and installing additional modules to it is tricky.

You should stick with the package that comes with your distro's official repositories. 

The RNA property error is more interesting, since I have not seen it before. Anyway, a fix is now upstream in `devel`, please re-download the code and try again.

**Comment by mr-intj-22** [comment] 2020-03-16 23:03
I am using elementary OS 5.1.2 Hera based on Ubuntu 18.04.3 LTS.
the modified devel solved the 'enum' error but raised a new one.
This happens when I try to enable the addone

`Read prefs: /home/mrintj//.config/blender/2.83/config/userpref.blend
BLENDYN::plotlib.py: could not import cairosvg. Plots will only be savedin .svg format, and not displayed in Blender UI.
TypeError: EnumProperty(..., default='TIME HISTORY'): not found in enum members
Traceback (most recent call last):
  File "/usr/share/blender/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/mrintj/.config/blender/2.83/scripts/addons/blendyn-devel/__init__.py", line 44, in <module>
    from . blendyn      import *
  File "/home/mrintj/.config/blender/2.83/scripts/addons/blendyn-devel/blendyn.py", line 307, in <module>
    bpy.utils.register_class(BLENDYN_PG_plot_vars)
ValueError: bpy_struct "BLENDYN_PG_plot_vars" registration error: plot_type could not register`
I am trying different Blender version, there's corruption perhaps.

P.S. downloaded Blender using this Repository!
`sudo add-apt-repository
ppa:thomas-schiex/blender
sudo apt-get update
sudo apt-get install blender`

**Comment by louisgag** [comment] 2020-03-17 08:37
Concerning the installation of python packages on a bundled python:
you should be able to install what you need by following the instructions on the [wiki page](https://github.com/zanoni-mbdyn/blendyn/wiki/Installing-Blendyn): under the "Update on installing Python packages with a precompiled Blender" header.

Concerning your error message: it says that you should install the cairosvg python package... Follow the installation instructions for the python packages on the wiki page I linked above.

**Comment by zanoni-mbdyn** [comment] 2020-03-17 08:40
My bad, I missed a couple of enum labels to fix. Now it should be fixed completely. 

About the cairosvg error, Louis pointed you to the right direction if you want to install cairosvg, but it is not mandatory and you should be able to safely ignore that error.

**Comment by mr-intj-22** [comment] 2020-03-17 09:33
Hi, problem solved (cheers)!
Thank you @zanoni-mbdyn and @louisgag for the assistance.

one more thing that I think it's related to the simulation itself, but let's be sure.
I have simulated the Pendulum example given in the website, and loaded the results, once I try to load the .log file I get this error,
`Error: Traceback (most recent call last):
  File "/home/mrintj/.config/blender/2.83/scripts/addons/blendyn-devel/blendyn.py", line 903, in invoke
    return self.execute(context)
  File "/home/mrintj/.config/blender/2.83/scripts/addons/blendyn-devel/blendyn.py", line 834, in execute
    ret_val, obj_names = parse_log_file(context)
  File "/home/mrintj/.config/blender/2.83/scripts/addons/blendyn-devel/baselib.py", line 404, in parse_log_file
    mbs.num_timesteps = mbs.num_rows/(mbs.num_nodes - disabled_nodes)
ZeroDivisionError: division by zero`

if it's not related to Blender/Blendyn we can close the issue.

**Comment by zanoni-mbdyn** [comment] 2020-03-17 09:41
I'll give it a try: do you mean the `rigidpendulum` model of the tutorial, or the `pendulum` model that you find in the *Misc* section of the examples?

**Comment by mr-intj-22** [comment] 2020-03-17 09:46
the `pendulum` one. file attached for reference.
[pendulum](https://github.com/zanoni-mbdyn/blendyn/files/4342654/pendulum.txt)

and the .log file
[pendulum.log](https://github.com/zanoni-mbdyn/blendyn/files/4342659/pendulum.log)

**Comment by zanoni-mbdyn** [comment] 2020-03-17 11:14
I can confirm that there is a bug with handling nodes whose output was disabled.
Right now, @mr-intj-22, you can comment out the "output, no" line at the end of node GROUND definition, to animate the model results. 

I'm closing this issue, as this error is not related to the Blendyn installation, and opening another one.

**Closed as completed by zanoni-mbdyn** 2020-03-17 11:14 UTC
